export const metadata = {
  title: 'Cadastrar | Meuestaciomed.com.br',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ptBR">
      <body>{children}</body>
    </html>
  )
}
